# Generated by Django 4.1.1 on 2022-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=500)),
                ('logo', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=500)),
                ('what_is_the_service', models.TextField(default='', max_length=5000)),
                ('contact_number', models.BigIntegerField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=300, null=True)),
                ('timeframe', models.CharField(choices=[('1_weeks', '1 Week'), ('2_weeks', '2 Weeks'), ('3_weeks', '3 Weeks'), ('4_weeks_plus', '4 Weeks+')], default='', max_length=100)),
                ('timeframe_2', models.DateField(default='2022-10-10')),
                ('aim', models.TextField(default='', max_length=5000)),
                ('products_product_images', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=500)),
                ('products_info', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=500)),
                ('pages_needed', models.CharField(blank=True, choices=[('about_page', 'About Page'), ('contact_page', 'Contact Page'), ('blog_page', 'Blog Page'), ('map_page', 'Map Page'), ('ecommerce_page', 'Ecommerce Page')], default='', max_length=500, null=True)),
            ],
        ),
    ]
