# Generated by Django 4.1.1 on 2022-09-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoformmodel',
            name='timeframe_2',
            field=models.DurationField(default='2022-10-10'),
        ),
    ]
