# Generated by Django 4.1.1 on 2022-09-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_infoformmodel_timeframe_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoformmodel',
            name='timeframe_2',
        ),
    ]
