# Generated by Django 4.1.1 on 2022-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_infoformmodel_timeframe_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoformmodel',
            name='would_you_like_one_created',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=100),
        ),
    ]
