# Generated by Django 4.1.1 on 2022-10-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_infoformmodel_would_you_like_one_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoformmodel',
            name='about_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infoformmodel',
            name='blog_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infoformmodel',
            name='contact_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infoformmodel',
            name='ecommerce_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infoformmodel',
            name='map_page',
            field=models.BooleanField(default=False),
        ),
    ]
