# Generated by Django 4.1.1 on 2022-10-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_infoformmodel_about_page_infoformmodel_blog_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoformmodel',
            options={'verbose_name_plural': 'Contact form info'},
        ),
        migrations.RemoveField(
            model_name='infoformmodel',
            name='about_page',
        ),
        migrations.RemoveField(
            model_name='infoformmodel',
            name='blog_page',
        ),
        migrations.RemoveField(
            model_name='infoformmodel',
            name='contact_page',
        ),
        migrations.RemoveField(
            model_name='infoformmodel',
            name='ecommerce_page',
        ),
        migrations.RemoveField(
            model_name='infoformmodel',
            name='map_page',
        ),
        migrations.AlterField(
            model_name='infoformmodel',
            name='pages_needed',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
